[mypy]
python_version = 3.12
strict_equality = True
warn_unused_ignores = True
show_error_codes = True

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-CoolProp.*]
ignore_missing_imports = True

[mypy-iapws.*]
ignore_missing_imports = True

[mypy-openpyxl.*]
ignore_missing_imports = True

[mypy-reportlab.*]
ignore_missing_imports = True
